package:
  name: pytest-qt
  version: "1.11.0"

source:
  fn: pytest-qt-1.11.0.zip
  url: https://pypi.python.org/packages/source/p/pytest-qt/pytest-qt-1.11.0.zip
  md5: c1be9518ab1915e22f8b8a6710d31626
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pytest-qt = pytest-qt:main
    #
    # Would create an entry point called pytest-qt that calls pytest-qt.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pytest >=2.7.0

  run:
    - python
    - setuptools
    - pytest >=2.7.0

test:
  # Python imports
  imports:
    - pytestqt

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/pytest-dev/pytest-qt
  license: GNU Lesser General Public License v3 (LGPLv3)
  summary: 'pytest support for PyQt and PySide applications'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
