package:
  name: pybtex
  version: !!str 0.18

source:
  fn: pybtex-0.18.tar.gz
  url: https://pypi.python.org/packages/source/p/pybtex/pybtex-0.18.tar.gz
  md5: f58ade6d487424a4a10612cb08bba5ce

requirements:
  build:
    - python
    - setuptools
    - pyyaml >=3.01

  run:
    - python
    - setuptools
    - pyyaml >=3.01
    - docutils
    - jinja2
    - pygments

test:
  # Python imports
  imports:
    - custom_fixers
    - pybtex
    - pybtex.backends
    - pybtex.bibtex
    - pybtex.charwidths
    - pybtex.database
    - pybtex.database.convert
    - pybtex.database.format
    - pybtex.database.input
    - pybtex.database.output
    - pybtex.docgen
    - pybtex.plugin
    - pybtex.style
    - pybtex.style.formatting
    - pybtex.style.labels
    - pybtex.style.names
    - pybtex.style.sorting
    - pybtex.tests
    - pybtex.tests.bst_parser_test
    - pybtex.tests.data
    - pybtex.tests.database_test

about:
  home: http://pybtex.sourceforge.net/
  license:  MIT License
  summary: 'A BibTeX-compatible bibliography processor in Python'
