package:
  name: latexcodec
  version: !!str 1.0.1

source:
  fn: latexcodec-1.0.1.tar.gz
  url: https://pypi.python.org/packages/source/l/latexcodec/latexcodec-1.0.1.tar.gz
  md5: fda0bfc55f94284a0cf34d6cca4b816c

requirements:
  build:
    - python
    - setuptools
    - six >=1.4.1

  run:
    - python
    - six >=1.4.1

test:
  imports:
    - latexcodec

about:
  home: https://github.com/mcmtroffaes/latexcodec
  license:  MIT License
  summary: 'A lexer and codec to work with LaTeX code in Python.'
